package com.samples.transactionflows.appmodule.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 15 00:52:53 EDT 2016
// ---------------------------------------------------------------------
public interface TransactionFlowAppModule extends ApplicationModule {
    void dumpAppModuleStatistics();
}
