package com.samples.transactionflows.appmodule.client;

import com.samples.transactionflows.appmodule.common.TransactionFlowAppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 15 00:52:53 EDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TransactionFlowAppModuleClient extends ApplicationModuleImpl implements TransactionFlowAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public TransactionFlowAppModuleClient() {
    }

    public void dumpAppModuleStatistics() {
        Object _ret = this.riInvokeExportedMethod(this,"dumpAppModuleStatistics",null,null);
        return;
    }
}
